<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back' => 'Назад',
    '200x50. This image will be displayed in place of the logo of the admin panel.' => '200x50. Это изображение будет отображено на месте логотипа в панели администратора.',
    'Admin Panel Module' => 'Модуль панели администратора',
    'Admin panel' => 'Панель администратора',
    'Admin. Access to dashboard' => 'Администратор. Доступ к главной странице',
    'Admin. Base access to admin panel' => 'Администратор. Базовый доступ',
    'Admin. Configuring modules' => 'Администратор. Настройка модулей',
    'Admin. System information' => 'Администратор. Информация о системе',
    'Admin. View log messages' => 'Администратор. Просмотр журнала сообщений.',
    'Administrator registration' => 'Регистрация администратора',
    'An internal server error occurred.' => 'Внутренняя ошибка сервера.',
    'Are you sure you want to delete all items?' => 'Вы уверены, что хотите удалить все элементы?',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту запись?',
    'Avatar' => 'Аватар',
    'CPU Usage' => 'Использование ЦПУ',
    'Configuration' => 'Конфигурация',
    'Created at' => 'Создан в',
    'DB' => 'БД',
    'Dashboard' => 'Главная',
    'Delete' => 'Удалить',
    'Delete all' => 'Удалить все',
    'Error' => 'Ошибка',
    'Failed to save.' => 'Ошибка сохранения.',
    'Hello<br />{username}' => 'Здравствуйте,<br />{username}',
    'IP' => 'IP',
    'Kernel' => 'Ядро',
    'Last day' => 'За день',
    'Last hour' => 'За час',
    'Last minute' => 'За минуту',
    'Last month' => 'За месяц',
    'Last week' => 'За неделю',
    'Level' => 'Уровень',
    'Log' => 'Журнал',
    'Logo image url' => 'URL картинки логотипа',
    'Logo text' => 'Текст логотипа',
    'Member since {0, date, MMM. yyyy}' => 'Участник с {0, date, MMMM yyyy}',
    'Memory' => 'Память',
    'Memory Usage' => 'Использование памяти',
    'Memory Usage. Used: {0}, total: {1}' => 'Память. Использовано: {0}, всего: {1}',
    'Message' => 'Сообщение',
    'More info' => 'Подробнее',
    'Name' => 'Имя',
    'No messages found.' => 'Сообщений не найдено.',
    'Nothing found.' => 'Ничего не найдено.',
    'OS' => 'ОС',
    'PHP' => 'PHP',
    'Port' => 'Порт',
    'Prefix' => 'Префикс',
    'Processor' => 'Процессор',
    'Profile' => 'Профиль',
    'Results' => 'Результаты',
    'Save' => 'Сохранить',
    'Search...' => 'Поиск...',
    'Search: {query}' => 'Поиск: {query}',
    'Settings saved successfully.' => 'Настройки успешно сохранены.',
    'Show phpinfo' => 'Показать phpinfo',
    'Sign out' => 'Выйти',
    'Sign up' => 'Зарегистрировать',
    'Software' => 'Программы',
    'Some settings have problems.' => 'Некоторые параметры имеют проблемы.',
    'Sort number' => 'Число для сортировки.',
    'Storage Usage. Used: {0}, total: {1}' => 'Хранилище. Использовано: {0}, всего: {1}',
    'Swap' => 'Swap',
    'System' => 'Система',
    'System date' => 'Системная дата',
    'System information' => 'Системная информация',
    'System message #{id}' => 'Системное сообщение #{id}',
    'System messages' => 'Системные сообщения',
    'System time' => 'Системное время',
    'The lower the number, the higher the menu item.' => 'Чем меньше число, тем выше пункт в меню.',
    'The requested system message does not exist.' => 'Запрашиваемое системное сообщение не существует.',
    'This text will be displayed in place of the logo of the admin panel.' => 'Этот текст будет отображен на месте логотипа в панели администратора.',
    'Time' => 'Время',
    'Timezone' => 'Часовой пояс',
    'To the website' => 'На сайт',
    'Toggle navigation' => 'Переключить навигацию',
    'Uptime' => 'Время работы',
    'Webserver' => 'Веб-сервер',
    'more info' => 'подробнее',
];
