<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '200x50. This image will be displayed in place of the logo of the admin panel.' => '200x50. Это изображение будет отображено на месте логотипа в панели администратора.',
    'Admin. Configuring modules' => 'Администратор. Настройка модулей',
    'Admin. System information' => 'Администратор. Информация о системе',
    'Configuration' => 'Конфигурация',
    'Failed to save.' => 'Ошибка сохранения.',
    'Logo image url' => 'URL картинки логотипа',
    'Logo text' => 'Текст логотипа',
    'Save' => 'Сохранить',
    'Settings saved successfully.' => 'Настройки успешно сохранены.',
    'Some settings have problems.' => 'Некоторые параметры имеют проблемы.',
    'Sort number' => 'Число для сортировки.',
    'System status' => 'Информация о системе',
    'The lower the number, the higher the menu item.' => 'Чем меньше число, тем выше пункт в меню.',
    'This text will be displayed in place of the logo of the admin panel.' => 'Этот текст будет отображен на месте логотипа в панели администратора.',
    'Admin Panel Module' => 'Модуль панели администратора',
    'Admin panel' => 'Панель администратора',
    'Admin. Access to dashboard' => 'Администратор. Доступ к главной странице',
    'Admin. Base access to admin panel' => 'Администратор. Базовый доступ',
    'Admin. View log messages' => 'Администратор. Просмотр журнала сообщений.',
    'Administrator registration' => 'Регистрация администратора',
    'An internal server error occurred.' => 'Внутренняя ошибка сервера.',
    'Are you sure you want to delete all items?' => 'Вы уверены, что хотите удалить все элементы?',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту запись?',
    'Avatar' => 'Аватар',
    'Created at' => 'Создан в',
    'Dashboard' => 'Главная',
    'Delete' => 'Удалить',
    'Delete all' => 'Удалить все',
    'Error' => 'Ошибка',
    'Hello<br />{username}' => 'Здравствуйте,<br />{username}',
    'Last day' => 'За день',
    'Last hour' => 'За час',
    'Last minute' => 'За минуту',
    'Last month' => 'За месяц',
    'Last week' => 'За неделю',
    'Level' => 'Уровень',
    'Log' => 'Журнал',
    'Member since {0, date, MMM. yyyy}' => 'Участник с {0, date, MMMM yyyy}',
    'Message' => 'Сообщение',
    'More info' => 'Подробнее',
    'No messages found.' => 'Сообщений не найдено.',
    'Nothing found.' => 'Ничего не найдено.',
    'Prefix' => 'Префикс',
    'Profile' => 'Профиль',
    'Results' => 'Результаты',
    'Search...' => 'Поиск...',
    'Search: {query}' => 'Поиск: {query}',
    'Sign out' => 'Выйти',
    'Sign up' => 'Зарегистрировать',
    'System message #{id}' => 'Системное сообщение #{id}',
    'System messages' => 'Системные сообщения',
    'The requested system message does not exist.' => 'Запрашиваемое системное сообщение не существует.',
    'To the website' => 'На сайт',
    'Toggle navigation' => 'Переключить навигацию',
    'more info' => 'подробнее',
];
